import './globals.css';
import ToasterClient from '@/components/ToasterClient';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className='bg-zinc-900 text-foreground font-sans'>
        <header className='w-full bg-zinc-900 text-white py-6 shadow-md'>
          <div className='max-w-5xl mx-auto px-4 flex items-center justify-between'>
            <div className='text-3xl font-bold'>
              PULSE{' '}
              <span className='text-sm font-normal pl-4'>
                Purpose - Unity - Logic - Stress Style - Engagement
              </span>
            </div>
            {/* Optional: Add nav links here */}
          </div>
        </header>
        <main className='min-h-screen max-w-5xl mx-auto px-4 py-8'>
          {children}
          <ToasterClient /> {/* ✅ Now safe */}
        </main>
        <footer className='w-full text-center py-4 text-sm text-muted-foreground'>
          &copy; {new Date().getFullYear()} PULSE. All rights reserved.
        </footer>
      </body>
    </html>
  );
}
